name: isic_balanced
path: /repo/uncertainty_skin/data/isic_balanced/images
annotations_path: /repo/uncertainty_skin/data/isic_balanced/dataset.csv

img_size: 32
crop_scale: [0.8, 1.0]
crop_scale_tta: [0.8, 1.0]

batch_size: 32
num_workers: 0
target_name: target
class_names: [benign, malignant]
train_size: 0.7
val_size: 0.15
test_size: 0.15
seed: 42
bagging: True
bagging_size: 15000
num_tta: 100
noise: 0.0

fixed: False


# Продумать итоговую таблицу, где собираются методы с отдельным сидом
# Закончить с настройками
# Продумать таблицу с полным сидом. 
# Выигрывает CE, делаем выводы

# Добавить эксперимент с шумом в метках
# Смотрим на результат с UANLL, подсвечиваем преимущества 

