defaults:
  - _self_
  - dataset: isic_balanced
  - model: resnet
  - trainer: default

device: "cuda"

timm_models: ['resnet50', 'resnet18']

offline: False
clearml_model_id: a65ecaf5e7644d8398383cfc67385ad6