name: resnet50
num_classes: 2
pretrained: True

input_channel: 3
dropout_rate: 0.25
top_bn: False

loss_fun: TM+UANLL
weight: 0.9
label_smoothing: 0.1
lr: 0.0001

checkpoint_path: '/repo/uncertainty_skin/outputs/2024-10-30/15-40-48/checkpoints/resnet50_42_TM+UANLL_48fb9827-4fc4-4e19-a9b6-42655d3dbc16_epoch=11.ckpt'

optimizer_name: Adam

optimizer_hparams:
  weight_decay: 1e-4